name: Build, Test, and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dockerized-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/fruits-api:latest .

    - name: Run tests inside container
      run: |
        docker run --rm ghcr.io/${{ github.repository_owner }}/fruits-api:latest go test -v

    - name: Push image (if tests passed)
      run: docker push ghcr.io/${{ github.repository_owner }}/fruits-api:latest
